### ISSUE TITLE
[Feature Request] Use node 20 instead of node 16

### ISSUE THREAD

**Issue by kGarciaSemarchy** [levibostian/action-hide-sensitive-inputs#10]
Hi,
Thanks for you work about this Github action.
It's not really a feature but could you use an up to date node version (at least version 20) in order to fit the new requirements of Github:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Thx

**Comment by levibostian** [comment]
Agreed, that would be ideal.

If you're able, mind submitting a pull request with the change?

**Comment by levibostian** [comment]
I see a fork may have already done this. Could be a good reference.

https://github.com/joshmenden/action-hide-sensitive-inputs/commit/2f7464b0d433e6ed11b064d53338893917a1c7d4

**Comment by kGarciaSemarchy** [comment]
thx @levibostian for the merge. 
I seen that your CI after the merge is broken. Do you think that it's possible to release and push as soon as possible a new version of the github actions ?

**Comment by levibostian** [comment]
Deployment fixed. Latest release has been shipped.
